### ISSUE TITLE
change references on website to new url

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#243]
We now have https://blackpythondevs.com. We need to make changes throughout the website.

Don't worry about blog posts as the old url still works.

- [x] BlackPythonDevs/blackpythondevs.github.io#244
- [x] BlackPythonDevs/.maintainers#26
- [x] BlackPythonDevs/.maintainers#27
- [x] BlackPythonDevs/blackpythondevs.github.io#248
- [x] BlackPythonDevs/blackpythondevs.github.io#249

Happy to add any others that may appear

**Comment by oleksis** [comment]
I will check the change needed. Fast test and working...

![image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/e30590bc-1631-4188-b712-7d4c49bae4b8)

**Comment by kjaymiller** [comment]
oh sorry I meant anywhere and everywhere that we're linking to the github pages url.

Will update the issue

**Comment by oleksis** [comment]
🚧 WIP
