### ISSUE TITLE
Make changes to new carousel

### ISSUE THREAD

**Issue by TimOsahenru** [BlackPythonDevs/blackpythondevs.github.io#553]
Make changes to the new carousel feature based on the conversation in this PR https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/544

**TODOS:**
- [x] #580
- [x] The circle image makes it hard to see some images, it may be better as a full width image [[more ...]](https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/544#discussion_r1819108209)
- [x] With the new featured image setup, we should be able to use that for articles with
- [x] #579
- [x] #556
- [x] The section is margined inside the container making it smaller than the content near it. We can fix that by changing the width of the container from 85% to 100%
- [x] The default image seems to be a little buggy. Instead of giving the default image it like creates an image of the raw content... we can fix this by removing `default: post.content | split: '!' | first | split: '(' | last | split: ')' | first |`
- [ ] Investigate load time difference between using using bootstrap and traditional CSS [[more ...]](https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/544#discussion_r1819103879)
- [x] Use appropriate naming conventions for CSS file [[more ...]](https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/544#discussion_r1819109452)
- [x] #578
   - [ ] Test 1:
      - Add a small post as a demo (in test as a test case and destroy it after)
      - Wait and let it rebuild and then check to see if the default image is grabbed.
    - [ ] Test 2:
      - If you select the next_button you expect the image to change to a new one. Same for prev_button
    - [ ] Test 3:
      - That slides match the links in the recent posts section
    - [ ] Test 4:
      - When you click the links in the carousel they go to the corresponding webpages

**Comment by kjaymiller** [comment]
In order to test we need to make sure that we can compare the first active tile with the latest post...

currently in `_includes/latest-posts.html` the title header doesn't have a class which means that styling and testing is harder
